@startsalt
{
    { [ ( Foto ) ] } | {
        <b>Nombre:</b> Juanito Perez Tapioca
        <b>Partido:</b> Movimiento Transparencia
        <b>Cargo:</b> Asambleísta Nacional
        <b>Patrimonio:</b> $120,000.00
        [ Ver Antecedentes ]
    }
}
@endsalt