@startsalt
{
    <b>Participación Ciudadana (RF-06)</b>
    {
        Tu calificación: | [ ( ) 1 | ( ) 2 | ( ) 3 | (X) 4 | ( ) 5 ]
        Comentario: | "Me parece coherente su votación en educación."
        [ Publicar Comentario ]
    }
    {
        User1250 le da este politico: | [ ( ) 1 | ( ) 2 | ( ) 3 | (X) 4 | ( ) 5 ]
        Comentario: | "No me gusta la forma en la que hizo....."
        [ LIKE ]  | [ COMENTAR ]
    }
}
@endsalt